#!/bin/bash

CURRENT_WD=`pwd`;

SDK_BASE_URI="http://d1q6xku6craafi.cloudfront.net/";
SDK_BASE_NAME="AWSSDKForNet.Src_";
SDK_VERSION="$1";
SDK_ARCHIVE_FILE_EXTENSION="zip";
SDK_ARCHIVE_FILE_NAME=$SDK_BASE_NAME$SDK_VERSION.$SDK_ARCHIVE_FILE_EXTENSION;
SDK_README_TEMPLATE="$CURRENT_WD/README.template"
SDK_RELEASE_NOTES_URI="$(echo -n "$2" | sed 's/\//\\\//g')"

SDK_ARCHIVE_LOCATION=$SDK_BASE_URI$SDK_ARCHIVE_FILE_NAME;

rm -rf ../AWSSDKtemp;

cd ../ && mkdir AWSSDKtemp && cd AWSSDKtemp && wget $SDK_ARCHIVE_LOCATION && unzip $SDK_ARCHIVE_FILE_NAME && rm -f $SDK_ARCHIVE_FILE_NAME;
cd ../AWSSDKtemp && sed -e "s/@@SDK_VERSION@@/v$SDK_VERSION/g" -e "s/@@SDK_RELEASE_NOTES_URI@@/$SDK_RELEASE_NOTES_URI/g" $SDK_README_TEMPLATE > README;

cd $CURRENT_WD;

git checkout master && rsync -av ../AWSSDKtemp/* ./ --delete && git add . && git commit -a -m "Injection of v$SDK_VERSION source release of the AWSSDK for .NET" && rm -rf ../AWSSDKtemp;
git tag v$SDK_VERSION;
git push origin master && git push origin v$SDK_VERSION;

for branch in `git branch -a | egrep -v "maintenance|master" | sed -e 's/remotes\/origin\///'`; do 
	git checkout $branch && git merge master && git push origin && git checkout master && git branch -D $branch;
done

git checkout maintenance && git merge master && git push origin && git checkout master;
